### ISSUE TITLE
Device tree for AK4621

### ISSUE THREAD

**Issue by xistva02** [bnahill/audiopulse-embedded#12]
Hello,

I have a specific question about the incorporation of AK4621. Did you use some kind of device tree configuration for the AK4621 chip? Is it available somewhere?

Thanks.

Matej I.

**Comment by bnahill** [comment]
Matej,
I'm sorry it took so long to get back to you. I did not use a device tree for this--the various peripherals used to interact with the AK4621 were hard-coded into the software.
-Ben

**Comment by xistva02** [comment]
Hey Ben, thank you for the reply.

I was wondering if you used the codec.cpp file (and other includes) as a machine codec for ALSA? It seems different from the classic audio machine codec driver structure. I found no support for ak4621 in official Linux codecs git: https://github.com/torvalds/linux/tree/master/sound/soc/codecs

My last question is, did you use your codec.cpp file as a machine driver or do you know any source that would provide a driver for ak4621?

Thanks.

Matej I.

**Comment by bnahill** [comment]
Matej,
The AK4621 driver used in this project is actually a driver. It's just not one designed for Linux, where the various subcomponents (e.g., SPI and I2S) also need to conform to the Linux APIs for each (and support much broader use and configuration than I needed for this application, e.g., different sample rates and formats). If you're trying to add support to Linux, you have a driver to write. You can use this as a reference for the basics, but it is not a Linux driver.

That said, at the time, the AK4621 was an outstanding codec. I'm not sure what's come out since, but I would still recommend it based on my experience as long as it's still in production.
-Ben

**Comment by xistva02** [comment]
Thank you, Ben.

Best regards

Matej I.
